import { z } from "zod";

export const claimWorkflowStateSchema = z.enum([
  "submitted",
  "identity_pending",
  "channel_pending",
  "onsite_scheduled",
  "onsite_completed",
  "review_pending",
  "approved",
  "rejected",
  "changes_required",
]);

export const claimListFiltersSchema = z.object({
  search: z.string().trim().optional(),
  status: z.string().trim().optional(),
  companyId: z.coerce.number().int().positive().optional(),
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(10),
});

export const claimListItemSchema = z.object({
  claimRequestId: z.number().int(),
  companyId: z.number().int(),
  companyName: z.string(),
  branchId: z.number().int().nullable(),
  branchName: z.string().nullable(),
  branchAddress: z.string().nullable(),
  userId: z.string().nullable(),
  claimantName: z.string(),
  claimantEmail: z.string(),
  claimantPhone: z.string().nullable(),
  applicantRole: z.string().nullable(),
  source: z.string(),
  declaredChannelType: z.string().nullable(),
  declaredChannelValue: z.string().nullable(),
  preferredVerificationRoute: z.string().nullable(),
  statusName: z.string(),
  statusCode: z.string(),
  workflowState: claimWorkflowStateSchema,
  version: z.number().int().positive(),
  assignedReviewerId: z.string().nullable(),
  firstReviewerId: z.string().nullable(),
  secondReviewerId: z.string().nullable(),
  sensitiveCase: z.boolean(),
  otpChallengeId: z.string().nullable(),
  otpDestinationMasked: z.string().nullable(),
  otpExpiresAt: z.string().nullable(),
  submittedAt: z.string(),
  reviewedAt: z.string().nullable(),
  reviewedByName: z.string().nullable(),
  notes: z.string().nullable(),
  evidenceUrl: z.string().nullable(),
  hasVerificationRequest: z.boolean(),
  professionalFlowMetadata: z
    .record(z.string(), z.unknown())
    .nullable()
    .optional(),
  invitationId: z.number().int().nullable().optional(),
  invitationStatus: z.string().nullable().optional(),
});

export const claimListResultSchema = z.object({
  items: z.array(claimListItemSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});

export type ClaimListFiltersSchema = z.infer<typeof claimListFiltersSchema>;

export const claimDetailSchema = z.object({
  claimRequestId: z.number().int(),
  companyId: z.number().int(),
  companyName: z.string(),
  branchId: z.number().int().nullable(),
  branchName: z.string().nullable(),
  branchAddress: z.string().nullable(),
  branchPhone: z.string().nullable(),
  branchEmail: z.string().nullable(),
  userId: z.string().nullable(),
  claimantName: z.string(),
  claimantEmail: z.string(),
  claimantPhone: z.string().nullable(),
  applicantRole: z.string().nullable(),
  source: z.string(),
  declaredChannelType: z.string().nullable(),
  declaredChannelValue: z.string().nullable(),
  preferredVerificationRoute: z.string().nullable(),
  onsiteVisitScheduledAt: z.string().nullable(),
  onsiteVisitAddress: z.string().nullable(),
  onsiteContactPerson: z.string().nullable(),
  onsiteContactPhone: z.string().nullable(),
  onsiteVisitNotes: z.string().nullable(),
  statusId: z.number().int().nullable(),
  statusName: z.string(),
  statusCode: z.string(),
  workflowState: claimWorkflowStateSchema,
  version: z.number().int().positive(),
  assignedReviewerId: z.string().nullable(),
  firstReviewerId: z.string().nullable(),
  secondReviewerId: z.string().nullable(),
  sensitiveCase: z.boolean(),
  otpChallengeId: z.string().nullable(),
  otpDestinationMasked: z.string().nullable(),
  otpExpiresAt: z.string().nullable(),
  submittedAt: z.string(),
  reviewedAt: z.string().nullable(),
  reviewedById: z.string().nullable(),
  reviewedByName: z.string().nullable(),
  notes: z.string().nullable(),
  evidenceUrl: z.string().nullable(),
  verificationRequestId: z.number().int().nullable(),
  verificationStatusName: z.string().nullable(),
  verificationStatusCode: z.string().nullable(),
  verificationLevel: z.string().nullable(),
  professionalFlowMetadata: z.record(z.string(), z.unknown()).nullable(),
  invitationId: z.number().int().nullable().optional(),
  invitationStatus: z.string().nullable().optional(),
  invitationExpiresAt: z.string().nullable().optional(),
  invitationAcceptedAt: z.string().nullable().optional(),
});
