"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { NotificationReadBadge } from "./NotificationReadBadge";
import type { NotificationsListResult } from "@/features/backoffice/notifications/types";
type Props={data:NotificationsListResult};
function date(v:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"Fecha inválida":new Intl.DateTimeFormat("es-PE",{dateStyle:"medium",timeStyle:"short"}).format(d)}
export function NotificationsTable({data}:Props){const router=useRouter();const[busy,setBusy]=useState<number|null>(null);const[error,setError]=useState<string|null>(null);if(!data.items.length)return <div className="rounded-2xl border border-dashed border-neutral-300 bg-white p-8 text-center text-sm text-neutral-500">No se encontraron notificaciones con los filtros aplicados.</div>;async function mark(id:number){setBusy(id);setError(null);try{const r=await fetch(`/api/backoffice/notifications/${id}/read`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({read:true})});const p=await r.json().catch(()=>null);if(!r.ok||p?.ok===false)throw new Error(String(p?.error?.message??p?.error??p?.message??"No se pudo marcar como leída."));router.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar.")}finally{setBusy(null)}}return <div className="space-y-3">{error?<p className="text-xs text-rose-600">{error}</p>:null}<div className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-neutral-200"><thead className="bg-neutral-50"><tr>{["Notificación","Usuario","Tipo","Estado","Creada","Entregada","Acción"].map(h=><th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-neutral-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100 bg-white">{data.items.map(item=><tr key={item.id} className="hover:bg-neutral-50"><td className="px-4 py-4 text-sm text-neutral-700"><p className="font-medium text-neutral-900">{item.title??"Sin título"}</p>{item.message?<p className="mt-1 line-clamp-2 text-xs text-neutral-500">{item.message}</p>:null}</td><td className="px-4 py-4 text-sm"><p className="font-medium text-neutral-900">{item.userName??"Sistema / sin usuario"}</p><p className="mt-1 text-xs text-neutral-500">{item.userEmail??"—"}</p></td><td className="px-4 py-4 text-sm text-neutral-700">{item.typeName??"Sin tipo"}</td><td className="px-4 py-4"><NotificationReadBadge read={item.read}/></td><td className="px-4 py-4 text-sm text-neutral-700">{date(item.createdAt)}</td><td className="px-4 py-4 text-sm text-neutral-700">{date(item.deliveredAt)}</td><td className="px-4 py-4">{item.read?<span className="text-xs text-neutral-400">Sin acciones</span>:<Button type="button" size="sm" variant="secondary" loading={busy===item.id} onClick={()=>void mark(item.id)}>Marcar leída</Button>}</td></tr>)}</tbody></table></div></div></div>}
